### ISSUE TITLE
Create Map / Scatter Bar Visualization 

### ISSUE THREAD

**Issue by theryankelly** [MAPC/housing-submarkets#13]
The intent of this component is to visualize the relative distribution with and between submarkets of selected values. The user should be able to geographically select a tract and see corresponding information about that selection and compare it to other tracts in that subregion and other subregions.

We may allow the user to select between multiple values using a menu of some time.

Draft Example:
![image](https://user-images.githubusercontent.com/2421382/104818222-3d7a6400-57f4-11eb-8f14-d1869e9f60d3.png)

**Comment by atomtay** [comment]
To be clear, the darker/bolder purple line in the chart for submarket 3 represents the change in population (or whatever value depending on the selected chart) for the selected tract?

**Comment by theryankelly** [comment]
> To be clear, the darker/bolder purple line in the chart for submarket 3 represents the change in population (or whatever value depending on the selected chart) for the selected tract?

Yes. I envision each line in scatter-bar as a tract laid out in the bar based on the value and highlighted (dark purple in the example) if tract on map is highlighted. Drawing on the [Equity Indicators example](https://equityagenda.mapc.org/indicators) I see this highlight only going one-way map to bars, not also bars highlighting map.

Additionally, I think highlight should be based on hover rather than click, but I am open to change there.

**Comment by theryankelly** [comment]
Noticed the dropdown arrow currently remains fixed and doesn't move dynamically with the size of the text in the dropdown. Other than making it dynamic, would fixing it to the left be an option?

![image](https://user-images.githubusercontent.com/2421382/106777257-d1c93100-6612-11eb-9dd4-bb36cdbd95bd.png)

**Comment by atomtay** [comment]
Drat, that's annoying. Couple options:
- I *think* making the longest option first should set the dropdown arrow to an appropriate distance
- Statically setting `width` across the entire `select` would definitely do the trick, albeit not terribly gracefully.

I'm not sure right now which maps we want to display/what options we'll have (I'll bring it up at the meeting), so for now I'll go with Option 2 to quickly get us into a working state.

**Comment by theryankelly** [comment]
- How much flexibility do we have in styling the viz? I think if we increase the verticle high of the bars and make the selected tract be dark purple and higher than the background bar it will stand out more. I moved the label to the side to give more real estate. 

- Have we closed the door on being able to select in chart and highlight on map? Do we have any path to make that happen?

**current**
![image](https://user-images.githubusercontent.com/2421382/106965887-56e73f80-6712-11eb-8205-babbc7b2edc6.png)


**draft** ignore the filtered map to Boston. Would expect a full choropleth.
![image](https://user-images.githubusercontent.com/2421382/106965684-f6f09900-6711-11eb-9066-29033687c6d1.png)

**messing with bg and colors**
![image](https://user-images.githubusercontent.com/2421382/106966381-366bb500-6713-11eb-8282-0c04954fa49f.png)
![image](https://user-images.githubusercontent.com/2421382/106966593-a712d180-6713-11eb-914a-eea520b77e33.png)

**Comment by atomtay** [comment]
We have a little more flexibility in styling, but not much. I'm hesitant to move the titles to the side because while that buys us some more vertical space, it costs us horizontal space. The ticks are already very scrunched together in many places (which, to your second point, does take selecting a bar to highlight the map out of consideration). I can take another stab at making the selected tract's highlighted bar stand out more today, but we are somewhat limited by the shape the data winds up taking.

**Comment by atomtay** [comment]
Current state of scatterbar-map duo:
![Screen Shot 2021-02-08 at 8 49 10 AM](https://user-images.githubusercontent.com/10645500/107228387-9ea7e880-69ea-11eb-9530-8ec621f18187.png)

Still to do (required):
- [x] Adjust axis to properly display percentages
- [x] Determine and add remaining choropleths

Nice-to-haves:
- [ ] Reconsider map selection color (gold) to better match the map (maybe use the color of that tract's submarket?)
- [ ] Dynamic change width of selection box so down-caret is always slightly to the right of the current text
- [ ] Add ability to click on scatterbar position and have a tooltip/highlight the corresponding tract on the map

**Comment by theryankelly** [comment]
**Other Tasks:**
- [x] Need to finalize the selection of data to display.
Currently have 
- Median home value (medhv)
- Percent renter households (rhu_p)
- Percent year built prior to 1960 (yrblt59_p)
- Percent cash sales (cash17_p)
- Percent change in median home value (ch_medhv_P)

Nice to Have:
- [ ] Find a way to highlight each submarket depending on submarket page selection
- investigate highlight tract boundary with color
- investigate submarket outline highlight
- investigate obscuring other submarkets with overlay or toggle layer

**Comment by theryankelly** [comment]
Landed on:

![image](https://user-images.githubusercontent.com/2421382/109060481-7212f280-76b3-11eb-83cf-9c9a7e6e87ae.png)
