### ISSUE TITLE
Choose Submarket Colors

### ISSUE THREAD

**Issue by theryankelly** [MAPC/housing-submarkets#14]
Will need to select colors to represent each submarket. We do not intend to communicate a continuum with the colors. They should not be represented by a gradient or a chosen single value.

They will be used in maps and other design elements throughout the report to help reinforce what submarket is being discussed.

**Comment by atomtay** [comment]
Submarket colors are now set at `['#C7024E', '#043C30', '#80CDC1', '#F37B74', '#BF812D', '#8C510A', '#6EA1C9']`

**Comment by theryankelly** [comment]
@atomtay is going to take a stab at lightening the darkest green

**Comment by atomtay** [comment]
Submarket colors adjusted to 
```
const submarketColors = {
  1: '#C7024E',
  2: '#80CDC1',
  3: '#06614d',
  4: '#F37B74',
  5: '#BF812D',
  6: '#8C510A',
  7: '#6EA1C9',
};
```

Closing back out for now.
