### ISSUE TITLE
Create Map / Menu Visualization 

### ISSUE THREAD

**Issue by theryankelly** [MAPC/housing-submarkets#15]
The intent of this component is to both visualize especially the subregions but communicate an overview of each submarket and allow for navigation into more detailed submarket information.

Draft Example:
![image](https://user-images.githubusercontent.com/2421382/104818206-28053a00-57f4-11eb-94b5-b146aaadc7e0.png)

**Comment by atomtay** [comment]
Resolved in #17

**Comment by theryankelly** [comment]
Want to note here that we are not going to proceed with a tooltip on the home page map. Saving that functionality for the municipal explore page.
