### ISSUE TITLE
Policies Component

### ISSUE THREAD

**Issue by theryankelly** [MAPC/housing-submarkets#16]
Need to create a place in over and submarket reports for displaying policies. Have a couple of options depending on the number and priority.

Draft Examples:
![image](https://user-images.githubusercontent.com/2421382/104818303-cb564f00-57f4-11eb-99d2-35c83a9164b1.png)

![image](https://user-images.githubusercontent.com/2421382/104818311-d8733e00-57f4-11eb-816d-477aeeab1d30.png)

![image](https://user-images.githubusercontent.com/2421382/104818322-e2953c80-57f4-11eb-9901-9781e177aa94.png)

**Comment by theryankelly** [comment]
Need to start with a list of policies associated with each submarket.

**Comment by theryankelly** [comment]
[Airtable base](https://airtable.com/tbllgLW1rqK0pJu7p/viwiz6MTOUnSRgI7Z?blocks=hide) has been created for this purpose. We will look to embed the Airtbale into the Policy Strategy (Report) page.

**Comment by japartridge** [comment]
I saw the Airtable embed--it looks great, except it's showing the wrong matrix (new one with strategy groups on last tab).

**Comment by atomtay** [comment]
Oops! Swapped that out and pushed the correct view.

**Comment by theryankelly** [comment]
Can we consider this issue closed or are there other changes that need to be made to Airtable?

**Comment by atomtay** [comment]
Let's keep it open briefly---I just pushed up a simple design for the policy page that lets the user dig a little deeper into individual policy recs, would like to float it by folks at the check-in this morning to see if there's anything that needs adjusting
