### ISSUE TITLE
Create individual submarket pages

### ISSUE THREAD

**Issue by atomtay** [MAPC/housing-submarkets#23]
While the text/images (and likely charts) will change for each submarket will vary, the layout for each page will be the same and could be made into a component.

**Comment by theryankelly** [comment]
I wanted to highlight one feature we have discussed in conversation, but have not yet included in designs. That is: how to navigate between submarket pages without going back to the submarket menu. @atomtay @Kit-Un I wanted to get your thoughts on how we might include this ability and if it's worth pursuing.

### My initial thoughts are read next option something like:
![image](https://user-images.githubusercontent.com/2421382/106779964-819f9e00-6615-11eb-9640-dc3c368421aa.png)



### Or a choose from related option like:
![image](https://user-images.githubusercontent.com/2421382/106780010-8f552380-6615-11eb-96f8-7a61afe33cff.png)

**Comment by Kit-Un** [comment]
I think both designs can work. The second design does a good job in tying in the top of the page, however, if we have a really content heavy page I'd opt for the first design

**Comment by atomtay** [comment]
I prefer the first, though I would bring the navigation closer to the center and make it smaller
<img width="733" alt="Screen Shot 2021-02-03 at 12 55 26 PM" src="https://user-images.githubusercontent.com/10645500/106788593-24104f00-661f-11eb-90b8-f084bcced87a.png">

**Comment by Kit-Un** [comment]
Look at you using grids. SO PROUD - I can go either way.

**Comment by theryankelly** [comment]
With the draft payout created I am closing this issue. The related issues of issues #31, #32, #1, #2. #3 will affect this page and populate content and further development.
