### ISSUE TITLE
Submarket narratives

### ISSUE THREAD

**Issue by japartridge** [MAPC/housing-submarkets#3]
Write summaries of each submarket.

- [x] Draft copy to Karen
- [x] Tim review
- [x] Final copy to Annabelle

**Comment by atomtay** [comment]
Following up on our discussion of "buckets" of text vs individual narratives for each submarket, here's what I identified from the XD (please pardon the grid lines):

**Buckets**
- Short definition
- Longer definition
- List of key highlights/policies. This includes a short, bold title (such as "Growing Senior Population") and a sentence or two of explanation.
<img width="465" alt="Screen Shot 2021-02-03 at 4 09 58 PM" src="https://user-images.githubusercontent.com/10645500/106810102-7f9c0600-663a-11eb-929d-e711c055fbe9.png">
<img width="610" alt="Screen Shot 2021-02-03 at 4 10 11 PM" src="https://user-images.githubusercontent.com/10645500/106810104-80349c80-663a-11eb-919e-35509e0d7b55.png">

Between these two images (from the homepage and from a submarket page), the same definition can be used in both places. I see the "Key Highlights" list from the homepage panel being made of the short bold titles, but if you'd rather "Key Highlights" and "Key Policies" be different lists, that's totally fine--just let me know.

<img width="683" alt="Screen Shot 2021-02-03 at 4 10 27 PM" src="https://user-images.githubusercontent.com/10645500/106810568-25e80b80-663b-11eb-90fe-70a6ab2ad0d3.png">

The longer definition will be the first full paragraph(s) of a submarket page, before the map/chart duo.

**Free-form**

<img width="683" alt="Screen Shot 2021-02-03 at 4 10 46 PM" src="https://user-images.githubusercontent.com/10645500/106811008-b888aa80-663b-11eb-8dc6-fd707bf4e9e2.png">

The bulk of each submarket narrative (Below the map/chart combo) can be pretty free-form; they don't all need to have the same section titles, though if there is some overlap that's totally fine.

**Comment by japartridge** [comment]
- [ ] Draft copy to Karen
- [ ] Tim review
- [ ] Final copy to Annabelle
