### ISSUE TITLE
Add Social Cards

### ISSUE THREAD

**Issue by theryankelly** [MAPC/housing-submarkets#47]

**Comment by theryankelly** [comment]
Sharing some ideas:

![image](https://user-images.githubusercontent.com/2421382/109062466-f5cdde80-76b5-11eb-8814-e7e85d621863.png)

![image](https://user-images.githubusercontent.com/2421382/109062496-00887380-76b6-11eb-9f83-2a90eed8c4fa.png)

![image](https://user-images.githubusercontent.com/2421382/109062548-11d18000-76b6-11eb-894e-06bf664b4241.png)

**Comment by Kit-Un** [comment]
Something simple like #3 would work. I also like 2 but instead of 2 separate boxes, can we do one box and make it semi transparent?

**Comment by theryankelly** [comment]
@Kit-Un I like that idea are you picturing something like this:

![image](https://user-images.githubusercontent.com/2421382/109079691-4b61b580-76cd-11eb-9580-b2d94fc6f648.png)

Still need to refine copy

**Comment by Kit-Un** [comment]
If we're going to have a white overlay on the image then the purple box should be solid with no transparency. Alternatively, if the purple box is going to be transparent, then the image shouldnt have an overlay.

**Comment by theryankelly** [comment]
![image](https://user-images.githubusercontent.com/2421382/109165228-51957780-7749-11eb-916d-bf5239a35c8f.png)

![image](https://user-images.githubusercontent.com/2421382/109165264-59551c00-7749-11eb-8dee-ed2033bcd631.png)

Images are in Housing Submarket Idea Board XD for additional edits
